### ISSUE TITLE
Note dependency / requirements

### ISSUE THREAD

**Issue by the456gamer** [mrfdev/1MB#1]
Ie: os it is made for/tested against
What needs to be installed for it to run (if anything)

**Comment by mrfloris** [comment]
The wiki pages should clarify that.
https://github.com/mrfdev/1MB/wiki/1MB-BuildTools.sh#so-how-to-use-this

**Comment by mrfloris** [comment]
Which shell scripts was this for by the way?

Anyway, buildtools is a shell script, i make it only work for ubuntu and macos, if it works there for me, I am fine with it. 

It lets the user know if they dont have java, git, etc installed, and with version 2. that's available now it also spits out a link to tutorials on how to install most of those things. 

Once i have a bit more of a virtualization setup i can start to test it against other linux distributions. 

the 1mb start and 1mb minecraft ones have been updated to version 2 as well, they should spit out what it needs and doesn't have, feel free to give those a try and see if you expected it to do or say something before using it. 

(and maybe see if the wiki updated meanwhile to include what you were looking for, if not, point it out if you can and i will update it)

**Comment by mrfloris** [comment]
I think I got things covered, I just have to tidy things up
