### ISSUE TITLE
Invalid version support

### ISSUE THREAD

**Issue by mrfloris** [mrfdev/1MB#10]
We could potentially check against https://papermc.io/api/v1/paper to see if the version we're trying to get is actually a valid version. If not, figure out what the latest version is and ask to build that instead.

**Comment by the456gamer** [comment]
^ its now [https://papermc.io/api/v2/projects/paper](https://papermc.io/api/docs/swagger-ui/index.html?configUrl=/api/openapi/swagger-config)

**Comment by mrfloris** [comment]
Done https://github.com/mrfdev/1MB/commit/fb6416b34bc234de730fcbfe314ed25f9d76c8a4
